name: Deploy development stage

on:
  push:
    branches: [main, master]

defaults:
  run:
    shell: bash

jobs:
  run-dev-deploy:
    name: Run development deploy
    uses: ./.github/workflows/run-deploy.yml
    with:
      branch: ${{ github.ref_name }}
      stage: development
      node-version: '16.13.1'
    secrets:
      PIPELINE_AWS_ACCESS_KEY_ID: ${{ secrets.PIPELINE_AWS_ACCESS_KEY_ID }}
      PIPELINE_AWS_SECRET_ACCESS_KEY: ${{ secrets.PIPELINE_AWS_SECRET_ACCESS_KEY }}
      PIPELINE_AWS_REGION: ${{ secrets.PIPELINE_AWS_REGION }}
      ENV_FILE: ${{ secrets.DEV_ENV }}
      LITESTREAM_S3_BUCKET: ${{ secrets.LITESTREAM_S3_BUCKET }}
      LITESTREAM_S3_PATH: ${{ secrets.LITESTREAM_S3_PATH }}
      LITESTREAM_AWS_ACCESS_KEY_ID: ${{ secrets.LITESTREAM_AWS_ACCESS_KEY_ID }}
      LITESTREAM_AWS_SECRET_ACCESS_KEY: ${{ secrets.LITESTREAM_AWS_SECRET_ACCESS_KEY }}
